### ISSUE TITLE
Invalid line '  console.dir(${1:obj})'

### ISSUE THREAD

**Issue by volny** [grvcoelho/vim-javascript-snippets#11]
This is what I see after installing this plugin:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "~/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "~/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 896, in _track_change
    self._try_expand(autotrigger_only=True)
  File "~/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 788, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "~/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 668, in _snips
    source.ensure(filetypes)
  File "~/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 31, in ensure
    self._load_snippets_for(ft)
  File "~/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 53, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "~/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 70, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line '  console.dir(${1:obj})' in ~/.config/nvim/plugged/vim-javascript-snippets/snippets/javascript/console-dir.snippets:2
```

**Comment by muhammad-bin-zafar** [comment]
I see this too.
What should I do?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/74791818/208669292-3b40e6ef-5493-4db2-9525-3a25b59aeb91.png)
I see this after typing.

JavaScript, GNU/Linux.
( Not .js file, using shebang )
